# Project Configuration: teamspec-mvp
project_id: "teamspec-mvp"
name: "TeamSpec MVP"
description: |
  Minimum Viable Product for TeamSpec 2.0 Feature Canon operating model.
  Includes team configuration, prompt generation, and linting features.
status: active  # active, paused, completed, archived

stakeholders:
  - name: "Product Owner"
    role: "PO"
  - name: "Team Lead"
    role: "DEV"

roles:
  - BA
  - FA
  - SA
  - DEV
  - QA
  - SM
